<?php

/** @var Magento\Framework\View\Element\Template $block */

/** @var Adcend\Blog\ViewModel\Blog $blogViewModel */
$blogVm = $block->getData('blog_view_model');

?>

<section class="blog-index">
    <h1>Latest Post's</h1>
    <?php
    foreach($blogVm->list() as $blog):
        /** @var Adcend\Blog\Model\Blog $blog */
        ?>
    <div>
        <a
            href="<?= $block->getUrl("blog/post", [ "id" => $blog->getId() ]) ?>">
            <h2><?= $blog->getTitle() ?></h2>
        </a>
        <div>
            <time datetime=""><?= $blog->getCreatedAt() ?></time>
            &nbsp;
            |
            &nbsp;
            <span><?= $blog->getAuthor() ?></span>
        </div>
    </div>
    <?php endforeach; ?>
</section>